import Prism from 'prismjs'

import '@/assets/prism.css'

import 'prismjs/components/prism-bash.min'
import 'prismjs/components/prism-c.min'
import 'prismjs/components/prism-coffeescript.min'
import 'prismjs/components/prism-cpp.min'
import 'prismjs/components/prism-csharp.min'
import 'prismjs/components/prism-css.min'
import 'prismjs/components/prism-css-extras.min'
import 'prismjs/components/prism-git.min'
import 'prismjs/components/prism-go.min'
import 'prismjs/components/prism-http.min'
import 'prismjs/components/prism-ini.min'
import 'prismjs/components/prism-java.min'
import 'prismjs/components/prism-javascript.min'
import 'prismjs/components/prism-json.min'
import 'prismjs/components/prism-jsx.min'
import 'prismjs/components/prism-less.min'
import 'prismjs/components/prism-lua.min'
import 'prismjs/components/prism-markdown.min'
import 'prismjs/components/prism-nginx.min'
import 'prismjs/components/prism-objectivec.min'
import 'prismjs/components/prism-perl.min'
import 'prismjs/components/prism-php.min'
import 'prismjs/components/prism-php-extras.min'
import 'prismjs/components/prism-powershell.min'
import 'prismjs/components/prism-python.min'
import 'prismjs/components/prism-r.min'
import 'prismjs/components/prism-ruby.min'
import 'prismjs/components/prism-sass.min'
import 'prismjs/components/prism-scala.min'
import 'prismjs/components/prism-scss.min'
import 'prismjs/components/prism-sql.min'
import 'prismjs/components/prism-swift.min'
import 'prismjs/components/prism-typescript.min'
import 'prismjs/components/prism-vim.min'
import 'prismjs/components/prism-yaml.min'

export default Prism
